networks:
  monitoring:
services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped

  php-apache:
    image: php:apache
    container_name: php-apache
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php-apache.rule=Host(`cosa.catanduyago.duckdns.org`)"
    volumes:
      - ~/miapp:/var/www/html
    restart: unless-stopped

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - TZ=Etc/Utc
      - SUBDOMAINS=${SUBDOMAIN}
      - TOKEN=${TOKEN}
    volumes:
      - ./duckdns:/data
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    ports:
      - 3001:3001
    labels:
      - "traefik.enable=true"
      - "traefik.httpd.routers.uptime-kuma.rule=Host(`monitor.catanduyago.duckdns.org`)"
    restart: unless-stopped