version: "3.8"
services:
  dns:
    ports:
      - 53:53/udp
      - 5380:8080
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        #max-file: "10"
    environment:
      - "HTTP_USER=foo"
      - "HTTP_PASS=bar"
    restart: always
    image: jpillora/dnsmasq
  
  nodo1:
    image: nginx
    container_name: nodo1
    ports:
      - "8081:80" 
    volumes:
      - ./nodo1/index.html:/usr/share/nginx/html/index.html
  
  nodo2:
    image: nginx
    container_name: nodo2
    ports:
      - "8082:80"  
    volumes:
      - ./nodo2/index.html:/usr/share/nginx/html/index.html
networks:
  internal:
    driver: bridge
